#ifndef __org_libreoffice_example_sidebartest_idl__
#define __org_libreoffice_example_sidebartest_idl__

#include <org/libreoffice/example/XSideBarTest.idl>
module org { module libreoffice { module example { 	

	service SideBarTest : org::libreoffice::example::XSideBarTest {

	};

 }; }; };
#endif
