#ifndef __org_libreoffice_example_xsidebartest_idl__
#define __org_libreoffice_example_xsidebartest_idl__

module org { module libreoffice { module example { 	

	interface XSideBarTest {

	};

 }; }; };
#endif
